server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api

spring:
  application:
    name: deal
  config:
    import: optional:file:deal/.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: ${POSTGRES_SCHEMA}

url:
  conveyor: ${URL_CONVEYOR}