server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: conveyor
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

loan:
  global-rate: 21
  insurance-price: 100000
  insurance-rate: 2
  salary-rate: 1

logging:
  level:
    root: info
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
