server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api

spring:
  application:
    name: conveyor
  config:
    import: optional:file:conveyor/.env[.properties]
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

url:
  loan-properties: ${URL_LOAN_PROPERTIES}

logging:
  level:
    root: info
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
