version: '3'

networks:
  credit_conveyor:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  db:
    image: postgres:15.1-alpine
    container_name: postgres
    networks:
      - credit_conveyor
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - ${DB_LOCAL_PORT}:${DB_DOCKER_PORT}
    volumes:
      - ../deal/src/main/resources/preliquibase:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data