global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "credit-conveyor-deal"
    metrics_path: 'api/actuator/prometheus'
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "credit-conveyor-conveyor"
    metrics_path: 'api/actuator/prometheus'
    static_configs:
      - targets: ["host.docker.internal:8081"]
